DROP TABLE IF EXISTS USER_VERIFY_CODE;
CREATE TABLE USER_VERIFY_CODE (
  PHONE              VARCHAR(11)     NOT NULL COMMENT '手机号',
  MSG_TYPE           TINYINT(1)      NOT NULL DEFAULT 1 COMMENT '验证码类型：1-注册，2-登录，3-重置密码',
  VERIFY_CODE        VARCHAR(6)     NULL DEFAULT '' COMMENT '验证码',
  CREATE_TIME        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY USER_VERIFY_CODE(PHONE, MSG_TYPE)
) COMMENT '用户表';

DROP TABLE IF EXISTS USER_AUTH;
CREATE TABLE USER_AUTH (
  ID                 INTEGER         NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  PHONE              VARCHAR(11)     NOT NULL COMMENT '手机号',
  PASSWORD           VARCHAR(50)     NULL DEFAULT '' COMMENT '密码',
  PW_TRY_TIMES       TINYINT(1)      NULL DEFAULT 0 COMMENT '密码尝试次数',
  WX_OPENID			     VARCHAR(200)    NULL DEFAULT '' COMMENT '微信的openid',
  SESSION			       VARCHAR(50)     NULL DEFAULT '' COMMENT '用户会话',
  CREATE_TIME        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  REVISE_TIME        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (ID),
  UNIQUE KEY USER_AUTH(PHONE)
) COMMENT '用户表';

DROP TABLE IF EXISTS USER_INFO;
CREATE TABLE USER_INFO (
      USER_ID            INTEGER         NOT NULL COMMENT '用户ID',
      NAME               VARCHAR(20)     NULL DEFAULT '' COMMENT '昵称',
      HEAD_ICON			 VARCHAR(200)    NULL DEFAULT '' COMMENT '头像',
      BACKGROUND         VARCHAR(200)    NULL DEFAULT '' COMMENT '背景',
      PERSONAL_SIGN      VARCHAR(200)    NULL DEFAULT '' COMMENT '个性签名',
      SEX                TINYINT(1)      NULL DEFAULT 1 COMMENT '性别:0-女，1-男',
      BIRTHDAY           TIMESTAMP       NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生日',
      ADDRESS            VARCHAR(200)    NULL DEFAULT '' COMMENT '地址',
      REVISE_TIME        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
      PRIMARY KEY (USER_ID),
      UNIQUE KEY NAME(NAME)
) COMMENT '用户信息表';
