server:
  port: 8888

spring:
  datasource:
    jdbcUrl:
    driverClass: com.mysql.jdbc.Driver
    user:
    password:

wxconfig:
  appId:
  appSecret:

aliconfig:
  accessKeyId:
  accessKeySecret:
  registerMsgId: