server:
  port: 8889

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    jdbcUrl:
    driverClass: com.mysql.jdbc.Driver
    user: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #validationQuery: select 'x'
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

wxconfig:
  appId:
  appSecret:

aliconfig:
  accessKeyId:
  accessKeySecret:
  registerMsgId: