server:
  port: 8889

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    jdbcUrl: jdbc:mysql://49.235.164.57:3306/weiliao_user?useUnicode:true&characterEncoding:utf-8&zeroDateTimeBehavior:convertToNull&allowMultiQueries:true&autoReconnect:true
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: 1c732d4b9bc24c6a
    driver-class-name: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #validationQuery: select 'x'
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

wxconfig:
  appId: wxedfcddc996ccc43e
  appSecret: 9312ee4d79d6435cbcf67d19c13d8784

aliconfig:
  accessKeyId: LTAI4FhM6YePvCKCmZYitMwP
  accessKeySecret: T6Ddxgf4Zkpt2VaNM3YdhLSYXd3Jcx
  registerMsgId: SMS_173760507