DROP TABLE IF EXISTS WEILIAO;
CREATE TABLE WEILIAO (
    ID          INTEGER         NOT NULL COMMENT '主键ID',
    DETAIL      VARCHAR (500)   NOT NULL COMMENT '详细内容',
    MENTION_ID  INTEGER         NOT NULL COMMENT '@的人的ID',
    TOPIC_ID    INTEGER         NOT NULL COMMENT '话题ID',
    TYPE        INTEGER         NOT NULL COMMENT '微撩类型',
    PICS        TEXT            NOT NULL COMMENT '图片地址',
    VIDEOS      TEXT            NOT NULL COMMENT '视频地址',
    CREATE_TIME TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    REVISE_TIME TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间'
}

DROP TABLE IF EXISTS WEILIAO_TOPIC;
CREATE TABLE WEILIAO_TOPIC (
    ID          INTEGER         NOT NULL COMMENT '主键ID',
    NAME        VARCHAR (500)   NOT NULL COMMENT '详细内容',
    CREATOR_ID  INTEGER         NOT NULL COMMENT '创建者的ID',
    TYPE        VARCHAR (11)    NOT NULL COMMENT '话题类型',
    CREATE_TIME TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    REVISE_TIME TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间'
}